# Generated by Django 5.2.6 on 2025-09-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_update_coordinate_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photohunt',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='photohunt',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
