# Generated by Django 5.2.6 on 2025-09-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_photohunt_latitude_alter_photohunt_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photohunt',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='photohunt',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
