# Generated by Django 5.2.6 on 2025-09-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_photohunt_latitude_alter_photohunt_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='photohunt',
            name='difficulty',
            field=models.FloatField(blank=True, help_text='Difficulty level out of 5', null=True),
        ),
        migrations.AddField(
            model_name='photohunt',
            name='hint',
            field=models.TextField(blank=True, help_text='Optional hint for the photo hunt'),
        ),
    ]
